/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "store": string|undefined
  "storeGrid": string|undefined
  "storeItem": string|undefined
  "storeItemButton": string|undefined
  "storeItemPrice": string|undefined
  "storeItemTitle": string|undefined
}
